name: bompare
description: A simple command-line application.
# version: 0.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.6.0
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
  mockito: ^4.1.1
